.PHONY: clean All

All:
	@echo "----------Building project:[ DynamicLearn - Debug ]----------"
	@"$(MAKE)" -f  "DynamicLearn.mk"
clean:
	@echo "----------Cleaning project:[ DynamicLearn - Debug ]----------"
	@"$(MAKE)" -f  "DynamicLearn.mk" clean
